import type { FormEvent } from 'react';
import type { ScheduleEvent, Task, WorkspaceData } from './data';
import Icon from './Icon';
import { dateKey, tasksOnDay } from './useWorkspace';
import type { EventDraft, WorkspaceController } from './useWorkspace';
import { Empty, Modal, PanelTitle, clockTime, urgencyLabels } from './ui';

export type CalendarMode = 'month' | 'week';
export const moveDate = (date: Date, amount: number, mode: CalendarMode) => {
  const next = new Date(date);
  if (mode === 'month') { next.setDate(1); next.setMonth(next.getMonth() + amount); }
  else next.setDate(next.getDate() + amount * 7);
  return next;
};
export const eventsOnDay = (events: ScheduleEvent[], day: string) => {
  const start = new Date(`${day}T00:00`); const end = new Date(start); end.setDate(end.getDate() + 1);
  return events.filter(event => Date.parse(event.startAt) < end.getTime() && Date.parse(event.endAt) > start.getTime()).sort((a, b) => a.startAt.localeCompare(b.startAt));
};
export function CalendarPanel({ data, anchor, setAnchor, mode, setMode, selectedDay, setSelectedDay, editTask, editEvent, createEvent, detailed = false, expand }: { data: WorkspaceData; anchor: Date; setAnchor: (date: Date) => void; mode: CalendarMode; setMode: (mode: CalendarMode) => void; selectedDay: string; setSelectedDay: (day: string) => void; editTask: (task: Task) => void; editEvent: (event: ScheduleEvent) => void; createEvent: (day: string) => void; detailed?: boolean; expand?: () => void }) {
  const first = mode === 'month' ? new Date(anchor.getFullYear(), anchor.getMonth(), 1) : new Date(anchor);
  first.setHours(0, 0, 0, 0); first.setDate(first.getDate() - (first.getDay() + 6) % 7);
  const days = Array.from({ length: mode === 'month' ? 42 : 7 }, (_, i) => { const date = new Date(first); date.setDate(first.getDate() + i); return date; });
  const today = dateKey(new Date());
  const selectedTasks = tasksOnDay(data.tasks, selectedDay);
  const selectedEvents = eventsOnDay(data.events, selectedDay);
  const title = mode === 'month' ? anchor.toLocaleDateString('zh-CN', { year: 'numeric', month: 'long' }) : `${days[0].toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric' })} — ${days[6].toLocaleDateString('zh-CN', { month: 'numeric', day: 'numeric' })}`;
  return <section className={`panel calendar-panel ${detailed ? 'detailed' : ''}`}><PanelTitle title="时间视图" subtitle={title} action={<button className="text-button" onClick={detailed ? () => createEvent(selectedDay) : expand}>{detailed ? '添加日程' : '展开视图'}<Icon name={detailed ? 'plus' : 'arrow'} size={16}/></button>}/><div className="calendar-layout"><div className={`calendar-grid ${mode}`}><div className="weekday-row">{['一', '二', '三', '四', '五', '六', '日'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-days">{days.map(day => {
    const key = dateKey(day); const dayTasks = tasksOnDay(data.tasks, key); const dayEvents = eventsOnDay(data.events, key);
    return <div key={key} className={`calendar-day ${mode === 'month' && day.getMonth() !== anchor.getMonth() ? 'muted' : ''} ${key === today ? 'today' : ''} ${key === selectedDay ? 'selected-day' : ''}`}><button className="day-number" onClick={() => setSelectedDay(key)} aria-label={`${key}${key === today ? ' 今天' : ''}，${dayTasks.length} 项任务，${dayEvents.length} 项日程`} aria-pressed={key === selectedDay}>{day.getDate()}{key === today && <span className="sr-only">今天</span>}</button><div className="calendar-markers">{mode === 'week' || detailed ? <>{dayTasks.slice(0, 2).map(task => <button key={task.id} className={`calendar-chip task-chip ${task.completedAt ? 'done' : ''}`} onClick={() => editTask(task)} title={task.title}><span className={`tiny-dot ${task.urgency}`}/>{task.title}</button>)}{dayEvents.slice(0, 2).map(event => <button key={event.id} className="calendar-chip event-chip" onClick={() => editEvent(event)} title={event.title}>{clockTime(event.startAt)} {event.title}</button>)}{dayTasks.length + dayEvents.length > 4 && <button className="more-items" onClick={() => setSelectedDay(key)}>+{dayTasks.length + dayEvents.length - Math.min(dayTasks.length, 2) - Math.min(dayEvents.length, 2)} 项</button>}</> : <button className="day-dots" onClick={() => setSelectedDay(key)} aria-label={`查看 ${key} 的任务和日程`}>{dayTasks.slice(0, 3).map(task => <span key={task.id} className={`tiny-dot ${task.urgency} ${task.completedAt ? 'done' : ''}`}/>)}{dayEvents.length > 0 && <span className="tiny-dot event"/>}{dayTasks.length + dayEvents.length > 4 && <small>+</small>}</button>}</div></div>;
  })}</div></div><aside className="day-agenda"><div className="agenda-heading"><span>{selectedDay === today ? '今天的安排' : new Date(`${selectedDay}T12:00`).toLocaleDateString('zh-CN', { month: 'long', day: 'numeric' })}</span><small>{selectedTasks.length + selectedEvents.length} 项</small></div>{!selectedTasks.length && !selectedEvents.length ? <Empty title="留一点时间给自己" detail="选择日期查看任务，或添加日程。"/> : <div className="agenda-items">{selectedTasks.map(task => <button key={task.id} className={`agenda-item ${task.completedAt ? 'done' : ''}`} onClick={() => editTask(task)}><span className={`tiny-dot ${task.urgency}`}/><span><strong>{task.title}</strong><small>{urgencyLabels[task.urgency]} · {task.progress}%{task.dueAt && dateKey(new Date(task.dueAt)) === selectedDay ? ` · ${clockTime(task.dueAt)} 截止` : ''}</small></span></button>)}{selectedEvents.map(event => <button key={event.id} className="agenda-item" onClick={() => editEvent(event)}><span className="tiny-dot event"/><span><strong>{event.title}</strong><small>{clockTime(event.startAt)} — {clockTime(event.endAt)}{dateKey(new Date(event.startAt)) !== dateKey(new Date(event.endAt)) ? ' · 跨天日程' : ''}</small></span></button>)}</div>}<button className="text-button agenda-add" onClick={() => createEvent(selectedDay)}><Icon name="plus" size={15}/>添加日程</button></aside></div><footer className="panel-options calendar-options"><div className="calendar-navigation"><button className="icon-button" aria-label="上一段时间" onClick={() => setAnchor(moveDate(anchor, -1, mode))}><Icon name="left" size={16}/></button><button className="subtle-button" onClick={() => { setAnchor(new Date()); setSelectedDay(today); }}>今天</button><button className="icon-button" aria-label="下一段时间" onClick={() => setAnchor(moveDate(anchor, 1, mode))}><Icon name="right" size={16}/></button></div><div className="calendar-legend"><span><i className="tiny-dot shortterm"/>任务</span><span><i className="tiny-dot urgent"/>紧急</span><span><i className="tiny-dot event"/>日程</span></div><div className="segmented" aria-label="日历视图"><button className={mode === 'month' ? 'selected' : ''} onClick={() => setMode('month')}>月视图</button><button className={mode === 'week' ? 'selected' : ''} onClick={() => setMode('week')}>周视图</button></div></footer></section>;
}

export function EventEditor({ draft, setDraft, event, work, close }: { draft: EventDraft; setDraft: (draft: EventDraft) => void; event: ScheduleEvent | null; work: WorkspaceController; close: () => void }) {
  const submit = (e: FormEvent) => { e.preventDefault(); if (work.saveEvent(draft, event?.id ?? null)) close(); };
  return <Modal title={event ? '日程详情' : '添加日程'} close={close}><form className="form-grid" onSubmit={submit}><label>日程名称<input data-autofocus required maxLength={120} value={draft.title} onChange={e => setDraft({ ...draft, title: e.target.value })} placeholder="例如：项目讨论"/></label><div className="form-row"><label>开始时间<input required type="datetime-local" value={draft.startAt} onChange={e => setDraft({ ...draft, startAt: e.target.value })}/></label><label>结束时间<input required type="datetime-local" value={draft.endAt} onChange={e => setDraft({ ...draft, endAt: e.target.value })}/></label></div><label>备注<textarea rows={3} value={draft.notes} onChange={e => setDraft({ ...draft, notes: e.target.value })} placeholder="地点或补充信息"/></label><footer className="modal-actions">{event && <button type="button" className="danger-button" onClick={() => { if (work.deleteEvent(event)) close(); }}>删除日程</button>}<button type="button" className="secondary-button" onClick={close}>取消</button><button type="submit" className="primary-button">保存日程</button></footer></form></Modal>;
}
