import { useRef, useState } from 'react';
import type { FormEvent } from 'react';
import type { Settings } from './data';
import type { WorkspaceController } from './useWorkspace';
import Icon from './Icon';
import { PanelTitle } from './ui';

type ProfileTab = 'settings' | 'account' | 'data';
export function Profile({ work }: { work: WorkspaceController }) {
  const [tab, setTab] = useState<ProfileTab>('settings');
  return <div className="profile-page"><section className="profile-banner"><span className="profile-avatar">{work.data.settings.nickname.trim().slice(0, 1) || <Icon name="user" size={30}/>}</span><div><h2>{work.data.settings.nickname || '我的工作空间'}</h2><p>本地空间 · {work.data.tasks.length} 项任务 · 每天进步一点点</p></div><span className="guest-label">未登录</span></section>{tab === 'settings' ? <SettingsForm key={JSON.stringify(work.data.settings)} settings={work.data.settings} save={work.saveSettings}/> : tab === 'account' ? <LoginForm/> : <DataSettings work={work}/>}<div className="page-options"><div className="segmented" aria-label="我的页面选项">{([{ key: 'settings', label: '设置', icon: 'settings' }, { key: 'account', label: '账号登录', icon: 'user' }, { key: 'data', label: '数据管理', icon: 'database' }] as const).map(item => <button key={item.key} className={tab === item.key ? 'selected' : ''} onClick={() => setTab(item.key)}><Icon name={item.icon} size={16}/>{item.label}</button>)}</div></div></div>;
}
function SettingsForm({ settings, save }: { settings: Settings; save: (settings: Settings) => void }) {
  const [draft, setDraft] = useState(settings);
  const submit = (event: FormEvent) => { event.preventDefault(); save(draft); };
  return <section className="panel settings-panel"><PanelTitle title="把工作台调成你的节奏" subtitle="番茄钟与外观设置"/><form onSubmit={submit} className="form-grid"><label>昵称<input value={draft.nickname} maxLength={30} placeholder="怎么称呼你？" onChange={event => setDraft({ ...draft, nickname: event.target.value })}/></label><div className="settings-section"><h3><Icon name="focus" size={18}/>专注节奏</h3><div className="form-row"><label>专注时长（分钟）<input type="number" required min={1} max={180} value={draft.focusMinutes} onChange={event => setDraft({ ...draft, focusMinutes: Number(event.target.value) })}/></label><label>短休息（分钟）<input type="number" required min={1} max={180} value={draft.shortBreakMinutes} onChange={event => setDraft({ ...draft, shortBreakMinutes: Number(event.target.value) })}/></label></div><div className="form-row"><label>长休息（分钟）<input type="number" required min={1} max={180} value={draft.longBreakMinutes} onChange={event => setDraft({ ...draft, longBreakMinutes: Number(event.target.value) })}/></label><label>每几轮进行长休息<input type="number" required min={2} max={12} value={draft.longBreakEvery} onChange={event => setDraft({ ...draft, longBreakEvery: Number(event.target.value) })}/></label></div><p className="field-help">时长调整从下一轮生效，正在进行的计时会继续。</p><label className="setting-toggle"><span><strong>结束提示音</strong><small>完成一轮时，轻声提醒</small></span><input type="checkbox" role="switch" checked={draft.sound} onChange={event => setDraft({ ...draft, sound: event.target.checked })}/></label><label className="setting-toggle"><span><strong>自动开始休息</strong><small>完成专注后进入休息，下一轮专注手动开始</small></span><input type="checkbox" role="switch" checked={draft.autoBreak} onChange={event => setDraft({ ...draft, autoBreak: event.target.checked })}/></label></div><div className="settings-section"><h3><Icon name="sun" size={18}/>外观</h3><label>主题<select aria-label="主题" value={draft.theme} onChange={event => setDraft({ ...draft, theme: event.target.value as Settings['theme'] })}><option value="light">浅色</option><option value="dark">深色</option><option value="system">跟随系统</option></select></label></div><footer className="modal-actions"><button type="submit" className="primary-button">保存设置</button></footer></form></section>;
}
function LoginForm() {
  const [message, setMessage] = useState('');
  const [visible, setVisible] = useState(false);
  const submit = (event: FormEvent) => { event.preventDefault(); setMessage('登录服务尚未接入，暂时无法登录。你可以继续使用本地工作空间。'); };
  return <section className="panel login-panel"><span className="login-symbol"><Icon name="leaf" size={29}/></span><h2>欢迎回到你的空间</h2><p>账号登录将在接入服务后开放</p><form className="form-grid" onSubmit={submit}><label>邮箱<div className="input-with-icon"><Icon name="mail" size={17}/><input type="email" required autoComplete="username" placeholder="you@example.com"/></div></label><label>密码<div className="input-with-icon"><Icon name="lock" size={17}/><input aria-label="密码" type={visible ? 'text' : 'password'} required autoComplete="current-password" placeholder="输入你的密码"/><button type="button" className="text-button" onClick={() => setVisible(value => !value)}>{visible ? '隐藏' : '显示'}</button></div></label>{message && <p className="inline-notice" role="status">{message}</p>}<button type="submit" className="primary-button">登录<Icon name="arrow" size={17}/></button></form><p className="login-footnote">当前任务与设置保存在此浏览器。</p></section>;
}
function DataSettings({ work }: { work: WorkspaceController }) {
  const input = useRef<HTMLInputElement>(null);
  const [mode, setMode] = useState<'merge' | 'replace'>('merge');
  const legacyActive = work.data.sessions.some(session => !session.endAt);
  return <section className="panel data-panel"><PanelTitle title="照顾好你的记录" subtitle="本地备份与恢复"/><div className="data-counts"><span><strong>{work.data.tasks.length}</strong>任务</span><span><strong>{work.data.events.length}</strong>日程</span><span><strong>{work.data.sessions.length}</strong>专注记录</span></div><div className="data-action"><span className="data-action-icon"><Icon name="download" size={22}/></span><div><h3>导出备份</h3><p>备份任务、日程、专注记录与设置。</p></div><button className="secondary-button" onClick={work.exportData}>导出 JSON</button></div><div className="data-action"><span className="data-action-icon"><Icon name="upload" size={22}/></span><div><h3>恢复数据</h3><p>支持旧版备份，导入时自动升级任务格式。</p></div><button className="secondary-button" disabled={!work.writable || work.importing} onClick={() => input.current?.click()}>选择文件</button><input ref={input} hidden type="file" accept=".json,application/json" onChange={async event => { const file = event.target.files?.[0]; if (file) await work.importData(file, mode); event.target.value = ''; }}/></div>{legacyActive && <div className="inline-notice">有旧版尚未结束的计时。<button className="text-button" onClick={work.stopLegacyTimer}>结束旧计时</button></div>}<p className="field-help">更换设备或清除浏览器数据前，请导出备份。番茄钟的当前倒计时不包含在备份中。</p><footer className="panel-options"><label className="import-mode">导入方式<select disabled={!work.writable || work.importing} value={mode} onChange={event => setMode(event.target.value as typeof mode)}><option value="merge">按 ID 合并（保留当前设置）</option><option value="replace">替换全部数据与设置</option></select></label></footer></section>;
}
