import { useEffect, useMemo, useRef, useState } from 'react';
import type { FormEvent, ReactNode } from 'react';
import type { Priority, ScheduleEvent, Task, TaskCategory, WorkspaceData } from './data';
import Icon from './Icon';
import type { IconName } from './Icon';
import { blankEvent, blankTask, dateKey, isUrgent, localDateTime, useWorkspace } from './useWorkspace';
import type { EventDraft, TaskDraft } from './useWorkspace';

type Page = 'overview' | 'tasks' | 'calendar' | 'timeline' | 'report' | 'data';
type TaskView = 'all' | 'urgent' | 'planned' | 'longterm' | 'inbox' | 'completed';
const nav: { key: Page; text: string; icon: IconName }[] = [
  { key: 'overview', text: '总览', icon: 'home' }, { key: 'tasks', text: '任务中心', icon: 'check' }, { key: 'calendar', text: '日程表', icon: 'calendar' }, { key: 'timeline', text: '时间树', icon: 'clock' }, { key: 'report', text: '周报', icon: 'report' }, { key: 'data', text: '数据管理', icon: 'database' },
];
const views: { key: TaskView; text: string }[] = [
  { key: 'all', text: '全部任务' }, { key: 'urgent', text: '时间紧急' }, { key: 'planned', text: '近期计划' }, { key: 'longterm', text: '长期任务' }, { key: 'inbox', text: '收件箱' }, { key: 'completed', text: '已完成' },
];
const categories: Record<TaskCategory, string> = { inbox: '收件箱', planned: '近期计划', longterm: '长期任务' };
const priorities: Record<Priority, string> = { low: '低', normal: '普通', high: '高' };
const dateTime = (iso: string) => new Date(iso).toLocaleString('zh-CN', { month: 'numeric', day: 'numeric', hour: '2-digit', minute: '2-digit' });
const clockTime = (iso: string) => new Date(iso).toLocaleTimeString('zh-CN', { hour: '2-digit', minute: '2-digit', hour12: false });
const duration = (minutes: number) => `${Math.floor(minutes / 60)} 小时 ${String(minutes % 60).padStart(2, '0')} 分`;

export default function Workspace() {
  const work = useWorkspace();
  const { data, active, tick } = work;
  const [page, setPage] = useState<Page>('overview');
  const [view, setView] = useState<TaskView>('all');
  const [query, setQuery] = useState('');
  const [sort, setSort] = useState<'due' | 'priority' | 'newest'>('due');
  const [taskDraft, setTaskDraft] = useState<TaskDraft | null>(null);
  const [taskId, setTaskId] = useState<string | null>(null);
  const [eventDraft, setEventDraft] = useState<EventDraft | null>(null);
  const [eventId, setEventId] = useState<string | null>(null);
  const [anchor, setAnchor] = useState(new Date());
  const [calMode, setCalMode] = useState<'month' | 'week'>('month');
  const importRef = useRef<HTMLInputElement>(null);
  const today = dateKey(new Date());
  const pending = data.tasks.filter(t => !t.completedAt);
  const todayTasks = pending.filter(t => t.dueAt && dateKey(new Date(t.dueAt)) === today);
  const visibleTasks = useMemo(() => data.tasks.filter(t => {
    if (query && !`${t.title} ${t.notes}`.toLowerCase().includes(query.toLowerCase())) return false;
    if (view === 'completed') return !!t.completedAt;
    if (t.completedAt) return false;
    if (view === 'urgent') return isUrgent(t);
    return view === 'all' || t.category === view;
  }).sort((a, b) => {
    if (sort === 'priority') return ({ high: 0, normal: 1, low: 2 }[a.priority] - { high: 0, normal: 1, low: 2 }[b.priority]) || b.createdAt.localeCompare(a.createdAt);
    if (sort === 'newest') return b.createdAt.localeCompare(a.createdAt);
    return (a.dueAt ? Date.parse(a.dueAt) : Infinity) - (b.dueAt ? Date.parse(b.dueAt) : Infinity) || b.createdAt.localeCompare(a.createdAt);
  }), [data.tasks, query, view, sort, tick]);
  function editTask(task?: Task) { setTaskId(task?.id ?? null); setTaskDraft(task ? { title: task.title, notes: task.notes, category: task.category, priority: task.priority, dueAt: localDateTime(task.dueAt) } : blankTask()); }
  function editEvent(item?: ScheduleEvent, day?: string) { setEventId(item?.id ?? null); setEventDraft(item ? { title: item.title, notes: item.notes, startAt: localDateTime(item.startAt), endAt: localDateTime(item.endAt) } : blankEvent(day)); }
  function taskSubmit(e: FormEvent) { e.preventDefault(); if (!taskDraft) return; work.saveTask(taskDraft, taskId); setTaskDraft(null); }
  function eventSubmit(e: FormEvent) { e.preventDefault(); if (eventDraft && work.saveEvent(eventDraft, eventId)) setEventDraft(null); }
  const row = (task: Task) => <TaskRow key={task.id} task={task} active={active?.taskId === task.id} canStart={!active} edit={() => editTask(task)} complete={() => work.toggleTask(task)} start={() => work.startTask(task)} stop={() => work.stopTask(task)} remove={() => work.deleteTask(task)} />;
  const count = (key: TaskView) => key === 'completed' ? data.tasks.filter(t => t.completedAt).length : key === 'urgent' ? pending.filter(isUrgent).length : key === 'all' ? pending.length : pending.filter(t => t.category === key).length;
  return <div className="app-shell">
    <aside className="sidebar"><div className="brand"><span className="brand-mark"><Icon name="check" size={20}/></span><span>个人工作台</span></div><nav aria-label="主导航">{nav.map(item => <button key={item.key} className={`nav-item ${page === item.key ? 'active' : ''}`} onClick={() => setPage(item.key)} title={item.text}><Icon name={item.icon}/><span>{item.text}</span></button>)}</nav><div className="sidebar-bottom"><span className="online-dot"/>数据保存在此浏览器</div></aside>
    <main className="main-content"><header className="topbar"><span>我的空间 <span className="crumb">/ {nav.find(item => item.key === page)?.text}</span></span><span className="topbar-date">{new Date().toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' })}</span></header>
      {work.error && <div className="error-banner" role="alert">{work.error} 请检查浏览器存储权限。</div>}
      {!work.ready ? <div className="loading">正在载入工作台…</div> : <>
        {page === 'overview' && <><Heading eyebrow="MY WORKSPACE" title="今天，从这里开始" detail="查看重点任务，记录每一步进展。" action={<button className="primary-button" onClick={() => editTask()}><Icon name="plus" size={18}/>新建任务</button>}/><div className="stats-grid"><Stat label="待处理任务" value={pending.length} note="所有未完成任务"/><Stat label="时间紧急" value={pending.filter(isUrgent).length} note="3 天内到期及逾期"/><Stat label="今日日程" value={data.events.filter(e => dateKey(new Date(e.startAt)) === today).length} note="已安排的独立日程"/></div><div className="overview-grid"><section className="panel"><div className="panel-heading"><div><h2>今日任务</h2><p>今天到期的事项</p></div><button className="text-button" onClick={() => setPage('tasks')}>查看全部 <Icon name="right" size={15}/></button></div>{todayTasks.length ? todayTasks.map(row) : <Empty title="今天没有到期任务" detail="创建任务并设置截止时间。" action={<button className="secondary-button" onClick={() => editTask()}>新建任务</button>}/>}</section><section className="panel side-panel"><div className="panel-heading"><div><h2>近期日程</h2><p>接下来 7 天</p></div><button className="icon-button" aria-label="新建日程" onClick={() => editEvent()}><Icon name="plus"/></button></div>{data.events.filter(e => Date.parse(e.startAt) >= Date.now() - 86400000 && Date.parse(e.startAt) <= Date.now() + 7 * 86400000).sort((a,b) => a.startAt.localeCompare(b.startAt)).slice(0,5).map(e => <button key={e.id} className="upcoming-event" onClick={() => editEvent(e)}><span className="event-date">{new Date(e.startAt).getDate()}<small>{new Date(e.startAt).toLocaleDateString('zh-CN', { month: 'short' })}</small></span><span><strong>{e.title}</strong><small>{clockTime(e.startAt)} – {clockTime(e.endAt)}</small></span></button>)}{!data.events.length && <Empty title="暂无近期日程" detail="会议、预约等安排可在这里查看。"/>}</section></div>{active && <div className="active-banner"><span className="pulse"/>正在计时：<strong>{data.tasks.find(t => t.id === active.taskId)?.title}</strong><span>{duration(Math.max(0, Math.floor((tick - Date.parse(active.startAt)) / 60000)))}</span><button onClick={() => { const task = data.tasks.find(t => t.id === active.taskId); if (task) work.stopTask(task); }}>结束计时</button></div>}</>}
        {page === 'tasks' && <><Heading eyebrow="TASKS" title="任务中心" detail="按进度和时间安排你的待办事项。" action={<button className="primary-button" onClick={() => editTask()}><Icon name="plus" size={18}/>新建任务</button>}/><div className="task-layout"><aside className="task-categories">{views.map(v => <button key={v.key} className={view === v.key ? 'selected' : ''} onClick={() => setView(v.key)}><span>{v.text}</span><small>{count(v.key)}</small></button>)}</aside><section className="panel task-panel"><div className="task-toolbar"><div><h2>{views.find(v => v.key === view)?.text}</h2><p>{visibleTasks.length} 项任务</p></div><div className="task-tools"><label className="search-field"><Icon name="search" size={18}/><input value={query} onChange={e => setQuery(e.target.value)} placeholder="搜索任务" aria-label="搜索任务"/></label><select className="sort-select" aria-label="任务排序" value={sort} onChange={e => setSort(e.target.value as typeof sort)}><option value="due">截止时间</option><option value="priority">优先级</option><option value="newest">最近创建</option></select></div></div>{visibleTasks.length ? visibleTasks.map(row) : <Empty title={query ? '没有找到匹配的任务' : '这里还没有任务'} detail={query ? '试试其他关键词。' : '添加一项任务，开始整理工作。'} action={!query && view !== 'completed' ? <button className="secondary-button" onClick={() => editTask()}>新建任务</button> : undefined}/>}</section></div></>}
        {page === 'calendar' && <><Heading eyebrow="CALENDAR" title="日程表" detail="任务截止时间和独立日程，集中查看。" action={<button className="primary-button" onClick={() => editEvent()}><Icon name="plus" size={18}/>新建日程</button>}/><section className="panel calendar-panel"><div className="calendar-toolbar"><div className="calendar-control"><button className="icon-button" aria-label="上一段时间" onClick={() => setAnchor(moveDate(anchor, calMode === 'month' ? -1 : -7, calMode))}><Icon name="left"/></button><button className="icon-button" aria-label="下一段时间" onClick={() => setAnchor(moveDate(anchor, calMode === 'month' ? 1 : 7, calMode))}><Icon name="right"/></button><h2>{anchor.toLocaleDateString('zh-CN', { year: 'numeric', month: 'long' })}</h2><button className="today-button" onClick={() => setAnchor(new Date())}>今天</button></div><div className="segmented"><button className={calMode === 'month' ? 'selected' : ''} onClick={() => setCalMode('month')}>月</button><button className={calMode === 'week' ? 'selected' : ''} onClick={() => setCalMode('week')}>周</button></div></div><Calendar anchor={anchor} mode={calMode} data={data} onDay={day => editEvent(undefined, day)} onTask={editTask} onEvent={editEvent}/></section></>}
        {page === 'timeline' && <><Heading eyebrow="TIME TREE" title="时间树" detail="回看任务从创建到完成的每一步。"/><Timeline data={data} tick={tick}/></>}
        {page === 'report' && <><Heading eyebrow="WEEKLY REPORT" title="周报" detail="为后续的 Agent 自动总结预留空间。"/><section className="panel report-panel"><div className="report-icon"><Icon name="report" size={34}/></div><h2>周报功能即将加入</h2><p>后续可以基于任务、日程和时间记录生成每周总结。当前页面仅预留入口，不会自动分析或上传你的数据。</p><div className="report-preview"><span>未来周报将包括</span><div>完成的任务 <span>·</span> 投入时间 <span>·</span> 下周计划</div></div></section></>}
        {page === 'data' && <><Heading eyebrow="DATA" title="数据管理" detail="管理本地记录，并为将来的同步做好准备。"/><div className="data-grid"><section className="panel data-card"><div className="data-icon"><Icon name="download" size={22}/></div><h2>导出备份</h2><p>将任务、日程、计时和时间树记录打包为一个 JSON 文件。</p><button className="primary-button" onClick={work.exportData}><Icon name="download" size={18}/>导出 JSON</button></section><section className="panel data-card"><div className="data-icon"><Icon name="upload" size={22}/></div><h2>导入数据</h2><p>从工作台备份恢复数据。可选择替换现有数据或按 ID 合并。</p><button className="secondary-button" onClick={() => importRef.current?.click()}><Icon name="upload" size={18}/>选择 JSON 文件</button><input hidden ref={importRef} type="file" accept=".json,application/json" onChange={async e => { const file = e.target.files?.[0]; if (file) await work.importData(file); e.target.value = ''; }}/></section></div><section className="panel data-summary"><h2>当前数据</h2><div><span>任务 <strong>{data.tasks.length}</strong></span><span>日程 <strong>{data.events.length}</strong></span><span>计时记录 <strong>{data.sessions.length}</strong></span><span>时间节点 <strong>{data.activities.length}</strong></span></div><p>数据保存在当前浏览器。清除浏览器数据、更换设备或使用隐私窗口前，请先导出备份。</p></section></>}
      </>}
    </main>
    {work.notice && <div className="toast" role="status">{work.notice}</div>}
    {taskDraft && <Modal title={taskId ? '编辑任务' : '新建任务'} close={() => setTaskDraft(null)}><form onSubmit={taskSubmit} className="form-grid"><label>任务名称<input autoFocus required maxLength={120} value={taskDraft.title} onChange={e => setTaskDraft({ ...taskDraft, title: e.target.value })} placeholder="例如：整理项目资料"/></label><label>说明<textarea rows={3} value={taskDraft.notes} onChange={e => setTaskDraft({ ...taskDraft, notes: e.target.value })} placeholder="补充一些细节（可选）"/></label><div className="form-row"><label>所属模块<select value={taskDraft.category} onChange={e => setTaskDraft({ ...taskDraft, category: e.target.value as TaskCategory })}><option value="inbox">收件箱</option><option value="planned">近期计划</option><option value="longterm">长期任务</option></select></label><label>优先级<select value={taskDraft.priority} onChange={e => setTaskDraft({ ...taskDraft, priority: e.target.value as Priority })}><option value="normal">普通</option><option value="high">高</option><option value="low">低</option></select></label></div><label>截止时间<input type="datetime-local" value={taskDraft.dueAt} onChange={e => setTaskDraft({ ...taskDraft, dueAt: e.target.value })}/></label><div className="modal-actions"><button type="button" className="secondary-button" onClick={() => setTaskDraft(null)}>取消</button><button type="submit" className="primary-button">保存任务</button></div></form></Modal>}
    {eventDraft && <Modal title={eventId ? '编辑日程' : '新建日程'} close={() => setEventDraft(null)}><form onSubmit={eventSubmit} className="form-grid"><label>日程名称<input autoFocus required maxLength={120} value={eventDraft.title} onChange={e => setEventDraft({ ...eventDraft, title: e.target.value })} placeholder="例如：团队会议"/></label><div className="form-row"><label>开始时间<input required type="datetime-local" value={eventDraft.startAt} onChange={e => setEventDraft({ ...eventDraft, startAt: e.target.value })}/></label><label>结束时间<input required type="datetime-local" value={eventDraft.endAt} onChange={e => setEventDraft({ ...eventDraft, endAt: e.target.value })}/></label></div><label>备注<textarea rows={3} value={eventDraft.notes} onChange={e => setEventDraft({ ...eventDraft, notes: e.target.value })} placeholder="地点或补充信息（可选）"/></label><div className="modal-actions">{eventId && <button type="button" className="danger-button" onClick={() => { const item = data.events.find(e => e.id === eventId); if (item && work.deleteEvent(item)) setEventDraft(null); }}>删除日程</button>}<button type="button" className="secondary-button" onClick={() => setEventDraft(null)}>取消</button><button type="submit" className="primary-button">保存日程</button></div></form></Modal>}
  </div>;
}

function Heading({ eyebrow, title, detail, action }: { eyebrow: string; title: string; detail: string; action?: ReactNode }) { return <section className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{detail}</p></div>{action}</section>; }
function Stat({ label, value, note }: { label: string; value: number; note: string }) { return <div className="stat-card"><span>{label}</span><strong>{value}</strong><small>{note}</small></div>; }
function Empty({ title, detail, action }: { title: string; detail: string; action?: ReactNode }) { return <div className="empty-state"><div className="empty-symbol"><Icon name="check" size={25}/></div><strong>{title}</strong><p>{detail}</p>{action}</div>; }
function Modal({ title, close, children }: { title: string; close: () => void; children: ReactNode }) { useEffect(() => { const handler = (e: KeyboardEvent) => { if (e.key === 'Escape') close(); }; window.addEventListener('keydown', handler); return () => window.removeEventListener('keydown', handler); }, [close]); return <div className="modal-backdrop" onMouseDown={e => { if (e.target === e.currentTarget) close(); }}><div className="modal" role="dialog" aria-modal="true" aria-label={title}><header><h2>{title}</h2><button className="icon-button" onClick={close} aria-label="关闭"><Icon name="close"/></button></header>{children}</div></div>; }

function TaskRow({ task, active, canStart, edit, complete, start, stop, remove }: { task: Task; active: boolean; canStart: boolean; edit: () => void; complete: () => void; start: () => void; stop: () => void; remove: () => void }) {
  const overdue = task.dueAt && !task.completedAt && Date.parse(task.dueAt) < Date.now();
  return <div className={`task-row ${task.completedAt ? 'is-complete' : ''}`}><button className={`task-checkbox ${task.completedAt ? 'checked' : ''}`} onClick={complete} aria-label={task.completedAt ? `重新打开${task.title}` : `完成${task.title}`}><Icon name="check" size={14}/></button><div className="task-info"><button className="task-title" onClick={edit}>{task.title}</button><div className="task-meta"><span>{categories[task.category]}</span><span className={`priority-tag priority-${task.priority}`}>{priorities[task.priority]}优先级</span>{task.dueAt && <span className={overdue ? 'overdue' : ''}><Icon name="calendar" size={13}/>{dateTime(task.dueAt)}</span>}{active && <span className="active-label"><span className="pulse"/>计时中</span>}</div>{task.notes && <p className="task-notes">{task.notes}</p>}</div><div className="task-actions">{!task.completedAt && <><button className="small-action start" onClick={start} disabled={!canStart}><Icon name="play" size={15}/>开始</button><button className="small-action stop" onClick={stop} disabled={!active}><Icon name="stop" size={15}/>结束</button></>}<button className="icon-button" onClick={edit} aria-label={`编辑${task.title}`} title="编辑"><Icon name="edit" size={17}/></button><button className="icon-button danger-hover" onClick={remove} aria-label={`删除${task.title}`} title="删除"><Icon name="trash" size={17}/></button></div></div>;
}

function moveDate(date: Date, amount: number, mode: 'month' | 'week') { const next = new Date(date); if (mode === 'month') { next.setDate(1); next.setMonth(next.getMonth() + amount); } else next.setDate(next.getDate() + amount); return next; }
function Calendar({ anchor, mode, data, onDay, onTask, onEvent }: { anchor: Date; mode: 'month' | 'week'; data: WorkspaceData; onDay: (day: string) => void; onTask: (task: Task) => void; onEvent: (item: ScheduleEvent) => void }) {
  const first = mode === 'month' ? new Date(anchor.getFullYear(), anchor.getMonth(), 1) : new Date(anchor);
  first.setDate(first.getDate() - (first.getDay() + 6) % 7);
  const days = Array.from({ length: mode === 'month' ? 42 : 7 }, (_, i) => { const d = new Date(first); d.setDate(first.getDate() + i); return d; });
  return <div className={`calendar-grid ${mode}`}><div className="weekday-row">{['周一','周二','周三','周四','周五','周六','周日'].map(day => <span key={day}>{day}</span>)}</div><div className="calendar-cells">{days.map(day => { const key = dateKey(day); return <div className={`calendar-cell ${mode === 'month' && day.getMonth() !== anchor.getMonth() ? 'muted' : ''} ${key === dateKey(new Date()) ? 'is-today' : ''}`} key={key}><button className="day-number" onClick={() => onDay(key)} title="在此日期新建日程">{day.getDate()}</button><div className="day-items">{data.events.filter(e => dateKey(new Date(e.startAt)) === key).map(e => <button key={e.id} className="calendar-chip event-chip" onClick={() => onEvent(e)} title={`${e.title} · ${clockTime(e.startAt)}`}>{e.title}</button>)}{data.tasks.filter(t => t.dueAt && dateKey(new Date(t.dueAt)) === key).map(t => <button key={t.id} className={`calendar-chip task-chip ${t.completedAt ? 'done' : ''}`} onClick={() => onTask(t)} title={`${t.title} · ${dateTime(t.dueAt!)}`}>{t.title}</button>)}</div></div>; })}</div></div>;
}
function Timeline({ data, tick }: { data: WorkspaceData; tick: number }) {
  const items = [...data.activities].sort((a,b) => b.at.localeCompare(a.at));
  const days = [...new Set(items.map(a => dateKey(new Date(a.at))))];
  const labels = { created: '创建任务', started: '开始计时', stopped: '结束计时', completed: '完成任务', reopened: '重新打开', updated: '更新任务' };
  const total = data.sessions.reduce((sum, s) => sum + Math.max(0, Math.floor(((s.endAt ? Date.parse(s.endAt) : tick) - Date.parse(s.startAt)) / 60000)), 0);
  return <div className="timeline-layout"><section className="panel timeline-panel"><div className="panel-heading"><div><h2>活动记录</h2><p>按时间倒序排列</p></div><span>{items.length} 个节点</span></div>{days.length ? days.map(day => <div className="timeline-day" key={day}><h3>{new Date(`${day}T12:00`).toLocaleDateString('zh-CN', { year: 'numeric', month: 'long', day: 'numeric', weekday: 'long' })}</h3><div className="timeline-items">{items.filter(a => dateKey(new Date(a.at)) === day).map(a => <div className="timeline-item" key={a.id}><span className={`timeline-dot ${a.type}`}/><span className="timeline-time">{clockTime(a.at)}</span><div><strong>{labels[a.type]}</strong><p>{data.tasks.find(t => t.id === a.taskId)?.title}</p></div></div>)}</div></div>) : <Empty title="还没有时间记录" detail="创建任务并开始计时后，这里会出现进展轨迹。"/>}</section><aside className="panel timeline-summary"><h2>时间概览</h2><div><span>累计专注</span><strong>{duration(total)}</strong></div><div><span>计时次数</span><strong>{data.sessions.length}</strong></div><div><span>完成任务</span><strong>{data.tasks.filter(t => t.completedAt).length}</strong></div><p>“结束”只停止本次计时。完成任务请使用任务前的勾选按钮。</p></aside></div>;
}
